# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bola', models.PositiveSmallIntegerField()),
                ('ocorrencias', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estrelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrela', models.PositiveSmallIntegerField()),
                ('ocorrencias', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('nSorteio', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('dataSorteio', models.DateField()),
                ('bola1', models.PositiveSmallIntegerField()),
                ('bola2', models.PositiveSmallIntegerField()),
                ('bola3', models.PositiveSmallIntegerField()),
                ('bola4', models.PositiveSmallIntegerField()),
                ('bola5', models.PositiveSmallIntegerField()),
                ('estrela1', models.PositiveSmallIntegerField()),
                ('estrela2', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
