# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170511_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteio',
            name='premio9',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
