from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.inicio, name='inicio'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'core/logout.html'}, name='logout'),
    url(r'^changepassword/$', views.changePassword, name='changepassword'),
    url(r'^exitMenor$', views.exitMenor, name='exitMenor'),
    url(r'^homepage/$', views.homepage, name='homepage'),
    url(r'^areacomum/$', views.areacomum, name='areacomum'),
    url(r'^admin/$', views.admin, name='admin'),
    url(r'^registo$', views.registo, name='registo'),
    url(r'^novoRegisto$', views.novoRegisto, name='novoRegisto'),
    url(r'^loginpage$', views.loginpage, name='loginpage'),
    url(r'^loginview$', views.loginview, name='loginview'),
    url(r'^logoutview/$',views.logoutview, name='logoutview'),
    url(r'^submeterpass/$', views.submeterpass, name='submeterpass'),
	#url(r'^apostar/$', views.apostar, name='apostar'),
    url(r'^areapessoal/$', views.areapessoal, name='areapessoal'),
    url(r'^criarInfoBanc/$', views.criarInfoBanc, name='criarInfoBanc'),
    url(r'^criarInfoB/$', views.criarInfoB, name='criarInfoB'),
    url(r'^carregarsaldo/$', views.carregarsaldo, name='carregarsaldo'),
    url(r'^carregaS/$', views.carregaS, name='carregaS'),
    url(r'^editardados/$', views.editardados, name='editardados'),
    url(r'^editRegisto/$', views.editRegisto, name='editRegisto'),
    url(r'^mostardados$', views.mostrardados, name='mostrardados'),
	#url(r'^$', views.aposta, name='aposta'),
    url(r'^(?P<aposta_id>[0-9]+)/$', views.detalhe, name='detalhe'),
    url(r'^novaaposta/$', views.novaaposta, name='novaaposta'),
    url(r'^gravaAposta/$', views.gravaAposta, name='gravaAposta'),
    url(r'^enviarEmail/$', views.enviarEmail, name='enviarEmail'),
    url(r'^sugestoes/$', views.sugestoes, name='sugestoes'),
    url(r'^apostar/$', views.apostar, name='apostar'),
    url(r'^carregarficheiro/$', views.carregarficheiro, name='carregarficheiro'),
    url(r'^carregaF/$', views.carregaF, name='carregaF'),
    ]
